#!/bin/csh

####### NO WARRANTY  -  NEVER TESTED #####################
# clear-forward:  cleanup script for packing
# must be started in directory above forward (like rcs_colab)
##########################################################


rm forward/colab-fw-startup*

rm -r forward/fw-relfun/features

rm forward/demo/bench.bat

rm forward/demo/contour

rm forward/demo/features-magic.rf
