#!/bin/csh

####### NO WARRANTY  -  NEVER TESTED ######################
# clear-RFM: RFM cleanup script for packing       M.S.    #
# must be started in directory above RFM (like rcs_colab) #
###########################################################


/bin/rm -rf Old-RFM


/bin/rm -rf RFM/demo/mcad2nc # already exists in top/demo/...

/bin/rm -rf RFM/knownbugs

/bin/rm -rf RFM/emulator  # old NyWAM (v21, v22)


# keep only *.ps files in manual directory:

pushd .

cd RFM/docu/manual
mkdir ps
mv *.ps ps
/bin/rm -f *
/bin/rm -rf codegenerator
/bin/rm -rf compiler
/bin/rm -rf forward
/bin/rm -rf nywam
mv ps/* .
rmdir ps

popd
