

(gasm author "created from prelude.rf" code
      (      (.module user) 
	     (.import-module prelude)

             (.module prelude)
	     .static
	     cns/2
             (get_variable_temp 3 1)
             (put_list 1)
             (unify_value_temp 3)
             (unify_value_temp 2)
             (proceed)
             .proc
             continue/0
             (allocate 0)
             (put_constant |continue: | 1)
             (cl-extra wait 1)
             (put_constant true 1)
             (deallocate)
             (proceed)
             .proc
             predicate/1
             (allocate 1)
             (get_variable_perm 1 1)
             (cl-func operators 0)
             (get_variable_temp 2 1)
             (put_value_perm 1 1)
             (deallocate)
             (execute member/2)
             .proc
             member/2
             (set_index_number 2)
             (switch_on_term nil nil "label1493" nil "label1493")
             "label1493"
             (try 1 2)
             (trust 2 2)
             1
             (get_list 2)
             (unify_value_temp 1)
             (unify_variable_temp 3)
             (put_constant true 1)
             (proceed)
             2
             (allocate 0)
             (get_list 2)
             (unify_variable_temp 3)
             (unify_variable_temp 4)
             (put_value_temp 4 2)
             (call member/2 0)
             (put_constant true 1)
             (deallocate)
             (proceed)
             .proc
             tup2struct*/1
             (set_index_number 1)
             (switch_on_term nil nil "label1485" nil "label1485")
             "label1485"
             (try 1 1)
             (retry 2 1)
             (trust 3 1)
             1
             (allocate 2)
             (get_list 1)
             (unify_variable_perm 2)
             (unify_variable_perm 1)
             (put_value_perm 2 1)
             (call is-not-tupstruct/1 2)
             (put_list 1)
             (unify_value_perm 2)
             (unify_value_perm 1)
             (deallocate)
             (execute tup2struct/1)
             2
             (allocate 2)
             (get_list 1)
             (unify_variable_perm 2)
             (unify_variable_perm 1)
             (put_value_perm 2 1)
             (call is-tupstruct/1 2)
             (put_list 2)
             (unify_value_perm 1)
             (unify_nil)
             (put_list 1)
             (unify_value_perm 2)
             (unify_value_temp 2)
             (deallocate)
             (execute tup2struct/1)
             3
             (allocate 0)
             (get_list 1)
             (unify_variable_temp 2)
             (unify_variable_temp 3)
             (put_value_temp 2 1)
             (call var/1 0)
             (put_constant |functor unknown| 1)
             (cl-extra rf-print 1)
             (cl-extra rf-terpri 0)
             (fail)
             (deallocate)
             (proceed)
             .proc
             struct2tup*/1
             (allocate 0)
             (call struct2tup/1 0)
             (deallocate)
             (execute struct2tup*2/1)
             .proc
             struct2tup*2/1
             (set_index_number 1)
             (switch_on_term nil nil "label1476" nil "label1476")
             "label1476"
             (try 1 1)
             (trust 2 1)
             1
             (allocate 2)
             (get_list 1)
             (unify_variable_perm 2)
             (unify_variable_perm 1)
             (put_value_perm 2 1)
             (call is-not-tupstruct/1 2)
             (put_list 1)
             (unify_value_perm 2)
             (unify_value_perm 1)
             (deallocate)
             (proceed)
             2
             (allocate 2)
             (put_list 2)
             (unify_variable_perm 2)
             (unify_nil)
             (get_list 1)
             (unify_variable_perm 1)
             (unify_value_temp 2)
             (put_value_perm 1 1)
             (call is-tupstruct/1 2)
             (put_list 1)
             (unify_value_perm 1)
             (unify_value_perm 2)
             (deallocate)
             (proceed)
             .proc
             hi-struct-unify/2
             (set_index_number 2)
             (switch_on_term nil nil "label1468" nil "label1468")
             "label1468"
             (try 1 2)
             (retry 2 2)
             (trust 3 2)
             1
             (allocate 4)
             (get_variable_perm 2 1)
             (get_list 2)
             (unify_variable_perm 4)
             (unify_variable_perm 3)
             (call struct/1 4)
             (put_variable_perm 1 2)
             (get_list 2)
             (unify_value_perm 4)
             (unify_value_perm 3)
             (put_value_perm 2 1)
             (call struct2tup*/1 2)
             (get_value_perm 1 1)
             (put_unsafe_value_perm 1 1)
             (put_value_perm 2 1)
             (deallocate)
             (proceed)
             2
             (allocate 3)
             (get_variable_perm 1 1)
             (get_list 2)
             (unify_variable_perm 3)
             (unify_variable_perm 2)
             (put_value_perm 3 1)
             (call nonvar/1 3)
             (put_value_perm 1 1)
             (call var/1 3)
             (put_list 1)
             (unify_value_perm 3)
             (unify_value_perm 2)
             (call tup2struct*/1 1)
             (get_value_perm 1 1)
             (deallocate)
             (proceed)
             3
             (allocate 1)
             (get_variable_perm 1 1)
             (get_list 2)
             (unify_variable_temp 1)
             (unify_variable_temp 3)
             (call var/1 1)
             (put_value_perm 1 1)
             (call var/1 0)
             (put_constant |impossible higher order structure unification|
                           1)
             (cl-extra rf-print 1)
             (cl-extra rf-terpri 0)
             (fail)
             (deallocate)
             (proceed))) 
